name: test-short
on:
  pull_request_target:

env:
  GO_VERSION: '1.21'

jobs:
  test-short:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test-short
